# Q1. What is the distinction between a numpy array and a pandas data frame?
Is there a way to convert between the two if there is?


- Numpy arrays can be multi-dimensional whereas DataFrame can only be two-dimensional.

- Arrays contain similar types of objects or elements whereas DataFrame can have objects or multiple or similar data types.
- Both array and DataFrames are mutable.
- Elements in an array can be accessed using only integer positions whereas elements in a DataFrame can be accessed using both integer and index positions.
- DataFrames are mostly in the form of SQL tables and are associated with tabular data whereas arrays are associated with numerical data and computation.
- DataFrames can deal with dynamic data and mixed data types whereas arrays do not have the flexibility to handle such data


In [8]:
# Numpy array to pandas dataframe
#defining numpy array
import numpy as np
arr = np.array([[1,2,3],[3,24,1]])
arr
print(arr)
print(type(arr))
print("------------------------------------")
print("converting numpy to dataframe:")
import pandas as pd

df = pd.DataFrame(arr, columns = ['Column_A','Column_B','Column_C'])

print(df)
print(type(df))

print("[INFO] converting dataframe to numpy:")
array = np.array(df)
print(array)

[[ 1  2  3]
 [ 3 24  1]]
<class 'numpy.ndarray'>
------------------------------------
converting numpy to dataframe:
   Column_A  Column_B  Column_C
0         1         2         3
1         3        24         1
<class 'pandas.core.frame.DataFrame'>
[INFO] converting dataframe to numpy:
[[ 1  2  3]
 [ 3 24  1]]


In [ ]:
Q2. What can go wrong when an user enters in a stock-ticker symbol, and how do you handle it?





In [ ]:
#Q3. Identify some of the plotting techniques that are used to produce a stock-market chart.

#line chart
#bar chart
#candlestick chart



In [ ]:
#Q4. Why is it essential to print a legend on a stock market chart?

The legend displays information about the points that are currently hovered over or display information about datapooints



In [9]:
#Q5. What is the best way to limit the length of a pandas data frame to less than a year?


import pandas as pd

drinks = pd.read_csv('http://bit.ly/drinksbycountry')
print(drinks.info(memory_usage='deep'))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   country                       193 non-null    object 
 1   beer_servings                 193 non-null    int64  
 2   spirit_servings               193 non-null    int64  
 3   wine_servings                 193 non-null    int64  
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object 
dtypes: float64(1), int64(3), object(2)
memory usage: 30.5 KB
None


In [ ]:
#Q6. What is the definition of a 180-day moving average?

A moving average (MA) is a technical analysis indicator that helps smooth out price action by filtering out the “noise” from random price fluctuations.



In [ ]:
#Q7. Did the chapter's final example use "indirect" importing? If so, how exactly do you do it?

